import os
import json
import time
from datetime import datetime

REPORTS_DIR = "reports"
BLOCKED_IPS_FILE = "logs/blocked_ips.json"

# Ensure directories exist
os.makedirs(REPORTS_DIR, exist_ok=True)
os.makedirs("logs", exist_ok=True)

# Shared state for blocked IPs
blocked_ips = {}

# Load existing blocks if any
if os.path.exists(BLOCKED_IPS_FILE):
    try:
        with open(BLOCKED_IPS_FILE, "r") as f:
            blocked_ips = json.load(f)
    except:
        blocked_ips = {}

def save_blocked_ips():
    with open(BLOCKED_IPS_FILE, "w") as f:
        json.dump(blocked_ips, f, indent=4)

def block_ip(ip, reason):
    if ip not in blocked_ips:
        blocked_ips[ip] = {
            "reason": reason,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "status": "Blocked"
        }
        save_blocked_ips()
        create_incident_report(ip, reason)
        print(f">>> ACTION: IP {ip} has been BLOCKED due to {reason}.")
        return True
    return False

def unblock_ip(ip):
    if ip in blocked_ips:
        del blocked_ips[ip]
        save_blocked_ips()
        print(f">>> ACTION: IP {ip} has been UNBLOCKED.")
        return True
    return False

def create_incident_report(ip, reason):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = os.path.join(REPORTS_DIR, f"incident_{timestamp}_{ip.replace('.', '_')}.md")
    
    report_content = f"""# Incident Report: {reason}
## Summary
- **Date/Time**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Target IP (Attacker)**: {ip}
- **Threat Type**: {reason}
- **Automatic Action**: IP Address Blocked (Simulated)

## Details
A threat was detected by the CyberSecure Monitoring System. The source IP exhibited behavior consistent with **{reason}**. 
In accordance with Phase 5 Security Protocols, the IP has been added to the automated blacklist.

## Admin Actions Required
- [ ] Review traffic logs for {ip}
- [ ] Verify if this was a false positive
- [ ] Permanent Firewall update if threat is confirmed

---
*Generated by CyberSecure Autonomous Response System*
"""
    with open(report_path, "w") as f:
        f.write(report_content)
    
    # Also log to a general alerts file
    with open("logs/alerts.log", "a") as f:
        f.write(f"[{datetime.now()}] ALERT: {reason} from {ip}. Action: Blocked.\n")

def take_action(packet_info):
    """Entry point for the monitor to trigger response"""
    ip = packet_info["srcIp"]
    reason = packet_info["threatType"]
    
    if packet_info["risk"] != "Normal":
        block_ip(ip, reason)

def get_blocked_list():
    # Sort by timestamp descending so newest blocks are at the top
    sorted_blocks = sorted(
        [{"ip": ip, **details} for ip, details in blocked_ips.items()],
        key=lambda x: x.get("timestamp", ""),
        reverse=True
    )
    return sorted_blocks

def get_incident_reports():
    reports = []
    if not os.path.exists(REPORTS_DIR):
        return []
    
    for filename in os.listdir(REPORTS_DIR):
        if filename.endswith(".md"):
            reports.append({
                "id": filename,
                "name": filename.replace("incident_", "").replace(".md", ""),
                "timestamp": os.path.getmtime(os.path.join(REPORTS_DIR, filename))
            })
    return sorted(reports, key=lambda x: x["timestamp"], reverse=True)
